### ISSUE TITLE
How can I access the PDF?

### ISSUE THREAD

**Issue by webguy262** [cesarvr/pdf-generator#1]
I'm a bit new to app development so bear with me! How would I access a PDF created with type:share? Where does it go in the file system? Should I get a popup with sharing options, like Save PDF to iBooks? Thanks!

**Comment by cesarvr** [comment]
Hi, yes if you use the type:share option the User [(IOS share dialog)](https://youtu.be/gN094D-MdEY?t=11s) should take care of the PDF and the options available depends of what apps the user has installed, if you want control over the PDF generated you should use type:base64.
Cheers.
