### ISSUE TITLE
How to use examples given?

### ISSUE THREAD

**Issue by plhowk** [cesarvr/pdf-generator#10]
I'm very new to this and I'm just trying to learn js and phonegap/cordova.  But I have no idea where to put the example code.

Do I attach it to a button?  do I reference in the pdf.js in the index.html?  I'm new to this and very confused and google doesn't seem to help with this particular plugin.  

can anyone, not just cesarvr, help me out by explaining the use in a little more detail?

sorry if an "issue" is not the best place for this question but I didn't know where else to ask.

**Comment by cesarvr** [comment]
Hi @plhowk, you can start this example https://github.com/cesarvr/pdf-generator-example , it can help you as well take a look to the cordova project getting started cuide 

Cheers
