### ISSUE TITLE
Plugin is not working with images

### ISSUE THREAD

**Issue by kanika1901kapoor** [cesarvr/pdf-generator#11]
@cesarvr I am using this plugin to convert html to pdf on my cordova app, but unfortunately it does not work with the CSS property background or background-image.. I also tried img tag. But, no success.

**Comment by cesarvr** [comment]
is the image of the background accessible from the phone ? is in the phone Filesystem ? if yes, check case-sensitive problems with filename, and as a last resort try to load your template in webkit in the mobile browser and check if your image get loaded. 

take a look at this example, i'm able to load background images from google.com.
[pdf-generator-example](https://github.com/cesarvr/pdf-generator-example)

Cheers.

**Comment by mj6uc** [comment]
`Hello <img src="file:///var/mobile/Containers/Data/Application/6DF0F18C-7063-4993-9194-6949A1F76BE6/Library/NoCloud/C3tuFcdv_photo_004.jpg" width="100%" />Hello <img src="file:///var/mobile/Containers/Data/Application/6DF0F18C-7063-4993-9194-6949A1F76BE6/Library/NoCloud/e62xLcdv_photo_005.jpg" width="100%" />`

On iOS the above data when converted to PDF gives blank images even though the images are available on the path mentioned. What could be wrong?

**Comment by javierClavei** [comment]
+1

**Comment by bmagne-bobbies** [comment]
Any news from this problem ?

**Comment by MadeInFck** [comment]
Same trouble, anyone figured that out? My file path looks ok as usual missing icon is not displayed.
