### ISSUE TITLE
UIWebView deprecated

### ISSUE THREAD

**Issue by gatelli** [cesarvr/pdf-generator#112]
Hi, since the ITMS-90809: Deprecated API Usage of UIWebview (https://developer.apple.com/documentation/uikit/uiwebview) do you intend to remove all UIWebView API references and use WKWebView instead ?

From end of 2020 all apps using old API will be rejected.

Thx

**Comment by cesarvr** [comment]
The plugin currently use [WKWebView](https://github.com/cesarvr/pdf-generator/blob/master/src/ios/BNHtmlPdfKit.m#L49) so it should be fine.

**Comment by ravemir** [comment]
Hello, Cesar,

Was currently tracking down a warning in one of our submissions and found [this reference](https://github.com/cesarvr/pdf-generator/blob/c1d3d8a7edf84b2e2701cdf657ddb104fbc57522/src/ios/BNHtmlPdfKit.m#L435).

Unless protected by a preprocessor, which is evaluated at compile time, these will carry over to the generated IPA and be flagged upon submission.

Could you have another look at it, please?

**Comment by cesarvr** [comment]
Hi @gatelli ,

It should be solved on [version 2.1.1](https://www.npmjs.com/package/cordova-pdf-generator).
