### ISSUE TITLE
Usages of deprecated UIWebView

### ISSUE THREAD

**Issue by ravemir** [cesarvr/pdf-generator#115]
Hello, Cesar,

Was currently tracking down a warning in one of our submissions and found #112 . However, I still found [this reference](https://github.com/cesarvr/pdf-generator/blob/c1d3d8a7edf84b2e2701cdf657ddb104fbc57522/src/ios/BNHtmlPdfKit.m#L435) on the current master.

Unless protected by a preprocessor, which is evaluated at compile time, these will carry over to the generated IPA and be flagged upon submission.

Could you have another look at it, please?

**Comment by anapaulaweiss** [comment]
ao utilizar o plugin passando um html dependendo o tamanho do html aborta o aplicativo. Tem um limite de tamanho atualmente?
