### ISSUE TITLE
ReferenceError: pdf is not defined

### ISSUE THREAD

**Issue by pooldaemon** [cesarvr/pdf-generator#120]
I'm using Cordova 9.0.1, Android platform 8.0.0 and I've installed plugin as 
cordova plugin add cordova-pdf-generator 
but still getting the error "ReferenceError: pdf is not defined", I have other plugins working in the same project. in VSCode. Please help!

**Comment by cesarvr** [comment]
What do you get if you do ``cordova plugins`` ? 

```sh
cordova plugins                                                     
cordova-pdf-generator 2.1.1 "PDFGenerator"
cordova-plugin-compat 1.2.0 "Compat"
...
```
> The plugin should appear in the list. 

Also you can try reinstalling: 

```sh
cordova rm cordova-pdf-generator
cordova plugin add cordova-pdf-generator@2.1.1
```

**Comment by pooldaemon** [comment]
C:\CordovaProjects\ConsultaProductores2020>cordova plugins
cordova-pdf-generator 2.1.1 "PDFGenerator"
cordova-plugin-compat 1.2.0 "Compat"
cordova-plugin-file 6.0.1 "File"
cordova-plugin-whitelist 1.3.3 "Whitelist"

Still no luck after reinstalling... I have tried with version 1.9.8 and the error is the same.

**Comment by pooldaemon** [comment]
Sorry Cesar, I ommited     <script src="cordova.js"></script> 
from my index.html. It's working now!!!
