### ISSUE TITLE
Return saved file name/location

### ISSUE THREAD

**Issue by avijitcse** [cesarvr/pdf-generator#13]
Is it possible to return the saved file name/location in `onFinish` method for Android? 
From the print dialog user may choose any folder, create a new folder or change the file name at the time of saving. So how do I get that info.
I need to open the file in some viewer after user saves a file from print dialog.

**Comment by MikeMadez** [comment]
Do you got any luck?

**Comment by avijitcse** [comment]
@MikeMadez I am able to generate pdf using iText PDF library. But there is some licensing issue for using in Production.
Not sure this will help you or not.  You can visit below links:
http://www.skholingua.com/blog/using-itextpdf-generation-pdf-files-android
http://zacktutorials.blogspot.in/2014/07/android-read-and-write-pdf-file-using.html

**Comment by MikeMadez** [comment]
Thank you so much! I'll give it a try!


________________________________
De: avijitcse <notifications@github.com>
Enviado: miércoles, 19 de abril de 2017 09:32 a. m.
Para: cesarvr/pdf-generator
Cc: Miguel Duran; Mention
Asunto: Re: [cesarvr/pdf-generator] Return saved file name/location (#13)


@MikeMadez<https://github.com/MikeMadez> I am able to generate pdf using iText PDF library. But there is some licensing issue for using in Production.
Not sure this will help you or not. You can visit below links:
http://www.skholingua.com/blog/using-itextpdf-generation-pdf-files-android
http://zacktutorials.blogspot.in/2014/07/android-read-and-write-pdf-file-using.html

**Comment by cesarvr** [comment]
Hi All, I have released a new version of the pdf-generator-plugin now supports Android base64  so you can get the file back.
