### ISSUE TITLE
Android Share reports success, doesn't do anything

### ISSUE THREAD

**Issue by lordgreg** [cesarvr/pdf-generator#16]
Hi.

I've just installed the plugin and am testing it on Samsung Galaxy S6 6.0.1. Testing the function, I'm always getting success, but nothing appears on my screen:

```
window.pdf.htmlToPDF({
            url: "http://www.google.es",
            documentSize: "A4",
            landscape: "portrait",
            type: "share"
        }, function (data) { console.log('ok', data) }, function (data) { console.log('err', data) });

```

Output:
```
ok success
```

![image](https://cloud.githubusercontent.com/assets/480546/24445673/016cd504-146b-11e7-9ab0-8d8b1f13e23a.png)

**Additional data:**
plugin version: 1.0.11
cordova: 6.5.0
device and os version: Samsung Galaxy S6 6.0.1

**Comment by cesarvr** [comment]
I think the problem is related to a double call in an android method to generate a PDFAdapter, I was getting a random crashes when try to generate a PDF, I fix that problem for version 1.0.13, can you try that version to see if any luck. 

Cheers.
