### ISSUE TITLE
Android Use

### ISSUE THREAD

**Issue by matikbird** [cesarvr/pdf-generator#2]
This library seems fantastic!

I'd like to generate PDF in some random folder from a HTML string with this but,
how?

**Comment by cesarvr** [comment]
Android is not supported yet, :( sorry.

**Comment by LOG-TAG** [comment]
@cesarvr new to phonegap , now Android support available??

**Comment by cesarvr** [comment]
yes, take a look at this [example](https://github.com/cesarvr/pdf-generator-example).  Only problem is that android can't retrieve the base64.
