### ISSUE TITLE
How to display variable from javascript into the pdf

### ISSUE THREAD

**Issue by edwardpress** [cesarvr/pdf-generator#22]
This is the code I attempted to run        

var orderID = 12345;
var rando = "abc"

window.onload = function() {

            document.getElementById('contact-number').innerHTML = orderID;
            document.getElementById('things').innerHTML = rando;

        }

        document.addEventListener('deviceready', () => {

            //generate the pdf.
            cordova.plugins.pdf.htmlToPDF({
                    data: "<html> <h1>  Hello World  </h1> <h1> Order Number at <span id='contact-number'></span></h1> <h1> Random Variable </h1> <span id='things'></span></html>",

                },
                (sucess) => console.log('sucess: ', sucess),
                (error) => console.log('error:', error));
        });

Span id = "things"  and span id contact-number returns nothing

**Comment by cesarvr** [comment]
You need to pre-process the HTML with a template engine like [underscore template](http://underscorejs.org/#template) and then for example just doing:

`<your html and styles>.......<span id='things'><%=rando%></span>.......<your html and styles>`,

Compile it and then feed the result to the htmlToPDF::data method, look at the underscore web page for a more concrete documentation on how to use the compiler.

**Comment by edwardpress** [comment]
Thanks for the direction. I have attempted to install underscoreJS in ionic 2 and if I were to modify the code to such

        var rando = "ABC"
        var stuff= _.template('<p>Hello  World <%=rando %></p>');

    }


    document.addEventListener('deviceready', () => {


        //generate the pdf.
        cordova.plugins.pdf.htmlToPDF({
                data: "stuff",

            },
            (sucess) => console.log('sucess: ', sucess),
            (error) => console.log('error:', error));
    });

Is this the correct way?

**Comment by cesarvr** [comment]
yeah, thats the way , you just need to take the quotes out of ` data: "stuff"` , you can also practice in the chrome to check if the compilation , then just pass the value of the variable to the method.
