### ISSUE TITLE
Ionic 2  app crashing when calling htmlToPDF

### ISSUE THREAD

**Issue by citerio** [cesarvr/pdf-generator#26]
Hey Cesar, I already installed the plugin on my Ionic 2 project, but my app crashes when the htmlToPDF method is called, the OS just shows this message "Se ha detenido la Aplicacion"/ "The app has stopped". 

Thanks.

**Comment by cesarvr** [comment]
Hi @citerio 

Just made an update to the plugin can you test the latest version [1.1.0](https://www.npmjs.com/package/cordova-pdf-generator) just added some validations. 

Cheers.

**Comment by citerio** [comment]
Hey Cesar, ok, I'll do so, but How can I fetch the latest version?, I am running cordova plugin add cordova-pdf-generator but I'm still getting the old version 1.0.14.

**Comment by citerio** [comment]
I already managed to install the 1.1.1 version, but it is still crashing, I am running it on Android 4.0

**Comment by cesarvr** [comment]
Well sorry then I think the Printing capabilities are only available for[ api-level 19](https://developer.android.com/reference/android/print/PrintDocumentAdapter.html) - [Kikat](https://developer.android.com/about/versions/android-4.4.html).
