### ISSUE TITLE
cannot display image from firebase storage

### ISSUE THREAD

**Issue by musfandi** [cesarvr/pdf-generator#32]
Hiii, please help me...
cannot display image from firebase storage using pdf generator

`<img height="200" width="200" src="https://firebasestorage.googleapis.com/v0/b/firebase-musshop.appspot.com/o/images%2Fsurveydata%2FCBVoYsEVbQbS1YRHaVF2a4Gmnb82%2FpE6sEk7Q.jpg?alt=media&token=5c286dd6-b938-462b-8ca9-79a4713b7156">`
<img height="200" width="200" src="https://firebasestorage.googleapis.com/v0/b/firebase-musshop.appspot.com/o/images%2Fsurveydata%2FCBVoYsEVbQbS1YRHaVF2a4Gmnb82%2Fly4SHsZJ.jpg?alt=media&token=d4f5d131-0171-43e2-8c36-e74e2fb9999d">
sample image from firebase storage

image from https://image.ibb.co work like charm

**Comment by musfandi** [comment]
`import { Component } from '@angular/core';

import { NavController } from 'ionic-angular';
declare var cordova:any;
@Component({
  selector: 'page-home',
  templateUrl: 'home.html'
})
export class HomePage {
  constructor(public navCtrl: NavController) {
     
      var hContent = "<html> <h1>  Firebase hosting  </h1> " + 
                 "<img src='https://firebasestorage.googleapis.com/v0/b/firebase-musshop.appspot.com/o/images%2Fsurveydata%2FCBVoYsEVbQbS1YRHaVF2a4Gmnb82%2FpE6sEk7Q.jpg?alt=media&token=5c286dd6-b938-462b-8ca9-79a4713b7156' height='200' width='200' alt='drawing' />" +
                 "<h1>  ibb hosting  </h1> " + 
                 "<img height='200' width='200' src='https://image.ibb.co/nzEnqk/vdraw.jpg'>" +
                "</html>";
             console.log(hContent);

            document.addEventListener('deviceready', () => {             
                cordova.plugins.pdf.htmlToPDF({
                        data: hContent,
                        documentSize: "A4",
                        landscape: "portrait",
                        type: "base64"
                    },
                    (sucess) => console.log('sucess: ', sucess),
                    (error) => console.log('error:', error));
            });

   
  }

}
`
ionic 2 code

**Comment by musfandi** [comment]
from debug 
`https://firebasestorage.googleapis.com/v0/b/firebase-musshop.appspot.com/o/…a4Gmnb82/pE6sEk7Q.jpg?alt=media&token=5c286dd6-b938-462b-8ca9-79a4713b7156 Failed to load resource: the server responded with a status of 400 (Bad Request)`

`82%2FpE6sEk7Q.jpg`
change to 
`82/pE6sEk7Q.jpg`

how to prevent this process process ?
`So, "/" is actually a seperator, but "%2f" becomes an ordinary character that simply represents "/" character in element of your url.`

**Comment by cesarvr** [comment]
I have found the problem is because of the way I use to load assets in the webview, I have pushed a new [version (1.5.1) ](https://www.npmjs.com/package/cordova-pdf-generator)an I have tested against your image url and now should work.
