### ISSUE TITLE
file size

### ISSUE THREAD

**Issue by nnylip** [cesarvr/pdf-generator#40]
I'm creating a pdf that includes two jpgs (~120KB each) and 3 small text tables and the resulting pdf (attached) is 10.8MB (which is quite large as additional jpgs and tables need to be added). Is there an optimization feature available? 
[webview.pdf](https://github.com/cesarvr/pdf-generator/files/1173869/webview.pdf)

**Comment by cesarvr** [comment]
Thats very strange is this happening in iOS or Android? , can I you paste some of the template code you are using ?  Look [this example](https://github.com/cesarvr/pdf-generator-example) I'm embedding two images.

**Comment by nnylip** [comment]
Thanks for your response. On Android at this point. Attached is the main snippet. The for loops insert the data into the tables.

[sample.txt](https://github.com/cesarvr/pdf-generator/files/1176681/sample.txt)

**Comment by nnylip** [comment]
Do you have further thoughts on this? Using the attached ping, the attached pdf results. It is nearly 626MB. 7 pngs need to be included which would make for a huge file. A pdf created by pdfmake, a javascript library (which is very slow), results in a pdf less than 1MB. Really appreciate your help. 
![results4](https://user-images.githubusercontent.com/15943434/28672515-f29e7c2a-72ad-11e7-9f2f-52e98b78f4bc.png)
[webview.pdf](https://github.com/cesarvr/pdf-generator/files/1180071/webview.pdf)

**Comment by cesarvr** [comment]
can you previsualize the html in the browser ? I suspect that could be nested/overlapped images. A good way to debug to try opening your payload/page in the browser with [document.write()](https://developer.mozilla.org/en-US/docs/Web/API/Document/write) and check the DOM structure looking for overlapps or errors and check network traffic via chrome-tools to measure the page weight.  Maybe is a good chance for you to move all that string concatenation to an HTML file an require it using AJAX call.

**Comment by nnylip** [comment]
This was tried with the single png file and it is pretty plain vanilla. Can you try it and see if 
you get a smaller pdf?

**Comment by cesarvr** [comment]
I have made an example embedding a random number of images and the size is stable, as I mention beforeI think there should be a problem with the DOM structure or compression also the plugin is using behind the scene a webkit to load/render the page so the principle wysiwyg should apply here. 

[test_default.pdf](https://github.com/cesarvr/pdf-generator/files/1182877/test_default.pdf)

**Comment by nnylip** [comment]
Several tests were used to generate the pdf all of which yielding the large file, one test case was:

...
(pdf.htmlToPDF({
       data:'<img src="'+pdfArray[0]+'" />',
       documentSize: 'A4',
       landscape: 'portrait',
       type: 'share'
...

where pdfArray[0] is a base 64 string. I'm, not sure how the DOM comes into play with this example. 
Can you share the code used to create your example?

**Comment by nnylip** [comment]
It appears it is my issue in that I was getting these results with the android emulator. On the 
actual phone much smaller sizes are being obtained (which might substantiate your DOM comments). 
Thanks for you help and apologizes for your time. It is shaping up to be a great plugin!

**Comment by cesarvr** [comment]
Thanks, I'm glad that it work.
