### ISSUE TITLE
pdf with lots of pictures

### ISSUE THREAD

**Issue by pyummm** [cesarvr/pdf-generator#41]
In my project, customer does lots photos, describe each and generate document for printing with high res images. 

HTML text with image binaries inside become critically big for plugin, and 
depend of photos count/photos size app crashes during pdf generation.

I have decrease photos quality and size, but it pretty critical, because it show details of inspected stuff.

I use Ionic over IOS at Ipad Air 2

**Comment by cesarvr** [comment]
Hi, 
- when the plugin crash it give you some errors can you see the logs ?
- also when you said big images how big they are 4k, 1080p... and what is ammount of photos  ? 
- can you publish an html example of the crashing case ?

Cheers.

**Comment by pyummm** [comment]
Hi, due to deep investigations, i noticed what app crashes at save blob to device, my apologises, and thanks, you pushed my investigations to right way.
Issue has to be closed, plugin works properly at iPad Air 2.0 with conversion html sizes over 35mb.
Thanks!
