### ISSUE TITLE
generating pdf with list of images

### ISSUE THREAD

**Issue by Yewhenii** [cesarvr/pdf-generator#42]
Is it possible to create such number of pdf pages as amount of images?
My  generated pdf looks like that

![ezgif-1-227e20d892](https://user-images.githubusercontent.com/25609439/28879045-b88e4e92-77a9-11e7-9862-ff2ffdea03d9.gif)

I want to show one item per page

**Comment by cesarvr** [comment]
Sure, you just need to style your html with some centre div and predefined margins (top, bottom) and then tune it up using the print preview in Chrome (window.print()), that would give you an idea of the final result.

**Comment by Yewhenii** [comment]
Thanks for quick answer. Im trying to tune this right now but I hoped there is some tool or feature  to make each page separately or make some html template for the one and duplicate for another with different images (something like foreach)

**Comment by cesarvr** [comment]
Sorry, the plugin is using a offscreen Webkit so basically is a WYSIWYG. :)

**Comment by mj6uc** [comment]
Hello, 
I am using this as the data:
Hello <img src="file:///var/mobile/Containers/Data/Application/6DF0F18C-7063-4993-9194-6949A1F76BE6/Library/NoCloud/C3tuFcdv_photo_004.jpg" width="100%" />Hello <img src="file:///var/mobile/Containers/Data/Application/6DF0F18C-7063-4993-9194-6949A1F76BE6/Library/NoCloud/e62xLcdv_photo_005.jpg" width="100%" />

The image exists at that path. However the PDF comes up with only two "Hello" -- no images. What am I doing wrong?

**Comment by cesarvr** [comment]
@mj6uc did you try to load the image in Cordova's web browser, like in your index.html ?

**Comment by mj6uc** [comment]
Yes I can display the image in my template. It displays fine.

**Comment by bmagne-bobbies** [comment]
Did someone found a solution for this issue with images ?

**Comment by cesarvr** [comment]
@bmagne-bobbies this demo includes an  [example](https://github.com/cesarvr/pdf-generator-example) loading local files
