### ISSUE TITLE
Create multiple pages?

### ISSUE THREAD

**Issue by AndrewKasper** [cesarvr/pdf-generator#44]
Is there a way to tell it to create a new page and have it be part of the same document?

**Comment by cesarvr** [comment]
The plugin can't do that because is using Webkit for rendering so you are limited to what you can do in the browser. What you can do is, for example, to leave a big margin between the two zones you want in different pages and test the result in your browser until you get the desired effect.

**Comment by danielfnz** [comment]
any fix?
i want do create a new page in the document.

**Comment by cesarvr** [comment]
you need to leave a enough margin between the HTML elements to force the PDF renderer to push the content in separate pages
