### ISSUE TITLE
Is it posible to call and HTML located in the asset folder?

### ISSUE THREAD

**Issue by DetoloX** [cesarvr/pdf-generator#45]
That is my question.. instead of use html page in a server..  is posible to pass via URL a local HTML page?..

**Comment by cesarvr** [comment]
Hi, yes you can do it by passing something like `file:///android_asset/www/test.html` where www/ is where you put your html/js/css assets. Also you added an example [here](https://github.com/cesarvr/pdf-generator-example), just look the internal url example.
