### ISSUE TITLE
Not working after I updated the version to 1.5.4

### ISSUE THREAD

**Issue by mallikvarma** [cesarvr/pdf-generator#46]
Hi,
My app was crashing on android 4 with 1.0.4 version so I have updated the pdf-generator version to 1.5.4 with a hope that it would fix the crashing issue. But now pdf generator stopped working. Below is how I use to generate pdf from my app with 1.0.4. is it still correct with 1.5.4 ?

pdf.htmlToPDF({ data: myhtml, documentSize: "A4", landscape: "portrait", type: "base64" }, function(){ }, function(err){ alert('Could Not Generate PDF : '+err) });

**Comment by cesarvr** [comment]
what version of Andriod/iOS are you using ? did you try this [example](uhttps://github.com/cesarvr/pdf-generator-examplerl) it should work out-of-the-box ?

**Comment by mallikvarma** [comment]
I am using Android 6.0.1 and the above example is not accessible. it shows 404 error.

**Comment by cesarvr** [comment]
Sorry is there was a type in the URL this is the [correct](https://github.com/cesarvr/pdf-generator-example).

**Comment by mallikvarma** [comment]
that example is working in my device and only difference is that I was using 'type: base64'  instead of {type:"share"} for generating pdf from html which was interestingly working in 1.0.4 version but not in 1.5.4.   

Thanks for the help
