### ISSUE TITLE
Impossible to generate the PDF, message "Preparing preview..." never disappears

### ISSUE THREAD

**Issue by Adrian1995** [cesarvr/pdf-generator#47]
I try run your sample of Ionic (https://github.com/cesarvr/ionic2-basic-example) and nothing happens, the unique thing that happens is that the home screen is shown. I believe that is because the base64 of document is printed on console.

So, I try use the same sample, but changing the parameter type to "share", so, when I call the function is showed to me the message "Preparing preview..." indicating that the PDF is being generate, but the PDF never is generated for my and the message continues the same.

Can you help me to fix that ?

My android is on version 7.0. Do you think that can be this ?

**Comment by cesarvr** [comment]
Can you try by updating the plugin ?

**Comment by Adrian1995** [comment]
Ok, I will try.
