### ISSUE TITLE
Is it posible to change the file name in ios?

### ISSUE THREAD

**Issue by DetoloX** [cesarvr/pdf-generator#48]
Hi!... Is it posible to change the file name in Ios?

I only need to change the name file.pdf to another..

**Comment by cesarvr** [comment]
Sorry forgot to push that feature for the iOS version , If you need it now, and feel charitable you can send a PR (I don´t have a mac at the moment). 

To make it work you just need to read the property check [here](https://github.com/cesarvr/pdf-generator/blob/master/src/ios/PDFGenerator.m#L100) and pass the text to this [function ](https://github.com/cesarvr/pdf-generator/blob/master/src/ios/PDFGenerator.m#L59), compile it in xcode and you can get that feature working, don't forget to send a PR 👍.

**Comment by DetoloX** [comment]
Yeah.. I change the code in the plugin and it's works! At least in ios 9 and posterior..
In case someone needs it..

I change this line
NSString *filePath = [documentsDirectory stringByAppendingPathComponent:@"file.pdf"];

for this 2, you can pass the name with the filename plugin option..

  NSString* filename = [command argumentAtIndex:5 withDefault:@"file.pdf"];  
  NSString *filePath = [documentsDirectory stringByAppendingPathComponent:filename];
