### ISSUE TITLE
script or canvas drawing is not supported?

### ISSUE THREAD

**Issue by MeteorStartup** [cesarvr/pdf-generator#49]
A simple image screen with the image drawing with canvas is not printed.
I think maybe it's only support simple css and html page only.

is there any plan to support more simulated webbrowser based print?

**Comment by cesarvr** [comment]
Hi I didn't test that functionality before but, I was able to render this simple [canvas](http://corehtml5canvas.com/code-live/ch01/example-1.1/example.html)
![screenshot_20171011-095712](https://user-images.githubusercontent.com/3899337/31428418-efc4dc80-ae6a-11e7-9fa7-6d3084718e90.png), so maybe you need to check if the canvas is render correctly and if is in sync with the page onload, you maybe need to look for a way to block the page loading until the canvas rendering is finish.
