### ISSUE TITLE
Android Version

### ISSUE THREAD

**Issue by cara** [cesarvr/pdf-generator#5]
I really appreciate that you have published this plugin. 
Have you made any progress to implement the pdf generator for android devices, too?
That would be very helpful!

Thanks!

**Comment by cesarvr** [comment]
I very busy now :(, but yes,  i think it would be great to have Android support as well. I try with [flysaucer](https://github.com/flyingsaucerproject/flyingsaucer) but no luck , when i have some free time i will another look.

**Comment by kahuna76** [comment]
Also keen to have this working 👍

**Comment by cesarvr** [comment]
Version 1.0.0 now support PDF generation in android. Take a look to the [Demo](https://github.com/cesarvr/pdf-generator-example)
