### ISSUE TITLE
I can't Save as PDF

### ISSUE THREAD

**Issue by MarouaneSH** [cesarvr/pdf-generator#52]
Hi,
I can't save as pdf , the save button is disabled ? 
this is how it look

![capture](https://user-images.githubusercontent.com/23389104/32290148-5b30dabe-bef6-11e7-9435-e15c3854d3c8.PNG)

i tested it in android 4.4 and android 6 !
@cesarvr  Hope you can fix this issue

**Comment by cesarvr** [comment]
Thats because maybe you don’t have permission in that folder, by default in my emulator/phone the default folder is Download, try to change the folder and try again. 

Cheers.
