### ISSUE TITLE
Not Generating PDF

### ISSUE THREAD

**Issue by BrianMoreno1994** [cesarvr/pdf-generator#58]
Hi, I'm currently trying to generate a PDF from my Android device. Unfortunately, when I try to generate it nothing happens. This is the code I'm using:

```
let options = {
      documentSize: 'A4',
      type: 'share'
}

pdf.usingURL('http://192.168.1.171/table.php', options).then(() => alert('ok')).catch((err) => alert(err))
```

Any help will be greatly appreciated! :)

These are my cordova plugins installed:
```
cordova-pdf-generator 1.9.3 "PDFGenerator"
cordova-plugin-whitelist 1.3.3 "Whitelist"
```
Android Version:
`Android Version 7.0`

**Comment by cesarvr** [comment]
Hi, are you getting any error message ?, you can look for the error message by using [chrome remote debugger](https://developers.google.com/web/tools/chrome-devtools/remote-debugging/?hl=en) in your phone.

**Comment by BrianMoreno1994** [comment]
Thank for your reply. When using the remote debugger I get the following message in the console:

```
vendor.js:1 TypeError: pdf.usingURL is not a function
    at a. table (5.e6c91e714285ec609d3f.js:1)
    at a.n [as table] (vendor.js:1)
    at click (5.e6c91e714285ec609d3f.js:1)
    at a.e (vendor.js:1)
    at a.t.$emit (vendor.js:6)
    at a.click (vendor.js:11)
    at n (vendor.js:1)
    at e (vendor.js:1)
    at HTMLButtonElement.t._withTask.t._withTask (vendor.js:1)
```

**Comment by cesarvr** [comment]
Sorry about that,  I made a mistake in the documentation the real method is [fromURL](https://github.com/cesarvr/pdf-generator#pdffromurl-url-options-)  and [fromData](https://github.com/cesarvr/pdf-generator#pdffromdata-url-options-). , I have updated the documentation with the correct methods. Thank you! very much for reporting it. 👍

**Comment by BrianMoreno1994** [comment]
Perfect, but unfortunately it now gets stuck on the "Preparing preview..." screen. 

This is what I'm trying:

```
let options = {
      documentSize: 'A4',
      type: 'share'
}

pdf.fromData('<html><h1>Hello World</h1></html>', options).then(() => alert('ok')).catch((err) => alert(err))
```

**Comment by cesarvr** [comment]
I found the problem, is in the alert, it will popup and focus the current WebKit, so basically the next view will wait until you click the alert, but the problem is you won't be able to go back. long history short if you want to get feedback choose **console.log**, DOM Modal like [SweetAlert2](https://limonte.github.io/sweetalert2/) or you can use a native [Progress Bar](https://www.npmjs.com/package/cordova-plugin-progress).

**Comment by BrianMoreno1994** [comment]
Ahh I see, thanks a lot for your help, it's working now. This is really an excellent plugin. I'm gonna for sure share your work! 👍

Thanks again!
