### ISSUE TITLE
EXC_BAD_ACCESS

### ISSUE THREAD

**Issue by MHDMAM** [cesarvr/pdf-generator#6]
Hi,

My app crash whenever I call this plugin, after debugging it, i'm getting `EXC_BAD_ACCESS` at line 53 of `BNHtmlPdfKit.m` because of this line:

L77: `pdfKit.failureBlock = failure;` of this function `saveHTMLAsPdf`.

- No errors on the console.
- Installed platforms: IOS 4.2.0

I don't have enough experience with ObjectiveC to go deeper and understand the problem,  could you please help.

Thanks

**Comment by cesarvr** [comment]
Sorry, I can't help you, i don't have access to that version of IOS, the most old version i have available is the 8.1. 

Can you upgrade?  that would solve the problem

**Comment by MHDMAM** [comment]
Ohh Sorry, you got it wrongly, 

> Installed platforms: IOS 4.2.0

Is the Cordova IOS platform, the latest one, and the device target is IOS 10.

**Comment by cesarvr** [comment]
Cool, I just update the problematic library can you test again please ?, just npm install the last version 0.9.8, I need to upgrade my Mac to Sierra to been able to test in IOS 10, if still doesn't work let me know. 

Cheers.

**Comment by MHDMAM** [comment]
Thanks, worked!
