### ISSUE TITLE
Is it possible to remove default print page margins?

### ISSUE THREAD

**Issue by Purushoth-ltr** [cesarvr/pdf-generator#7]
I need to remove a4 page default margins so that i can generate a pdf of full page. How can i remove the margins when converting the html to pdf?

**Comment by cesarvr** [comment]
If you mean the default margin (≈25mm) , sorry you can't you are constrained to the Webview way of doing the printing from HTML to PDF.

**Comment by Purushoth-ltr** [comment]
Thanks for the reply. Actually i removed the margins, but i don't know whether its the correct way. In the following function i removed the default margins and it worked.

`- (id)initWithPageSize:(BNPageSize)pageSize isLandscape:(BOOL)landscape {
	if (self = [super init]) {
		self.pageSize = pageSize;
		self.landscape = landscape;

		// Default 1/4" margins
		self.topAndBottomMarginSize = 0.0f * 0.0f;
		self.leftAndRightMarginSize = 0.0f * 0.0f;
	}
	return self;
}`

**Comment by cesarvr** [comment]
Interesting... can you please share a screenshot with the results you wanted achieved?, some trivial example if you can

**Comment by Purushoth-ltr** [comment]
I intended to print a report in IOS. Initially i got the pdf like this screenshot 1 with page margins.
![screen shot 2017-02-02 at 6 17 31 am](https://cloud.githubusercontent.com/assets/22051509/22547642/875b01bc-e910-11e6-9054-2837d61c4291.png)



Screenshot 2 without margins.
![screen shot 2017-02-02 at 6 02 45 am](https://cloud.githubusercontent.com/assets/22051509/22547645/8cab7610-e910-11e6-858e-64f51d944ff3.png)

Sorry for the poor images.

**Comment by cesarvr** [comment]
Ahh I get the idea, thats very nice use case I will try to add that as an option for IOS. Thanks!.

**Comment by Purushoth-ltr** [comment]
Thank you too @cesarvr

**Comment by gparasyris** [comment]
Hi @cesarvr , did you add this as an option for iOS? Thanks!

**Comment by jazzbpn** [comment]
Problem remains unsolved at iOS.
