### ISSUE TITLE
In iOS 9 plugin not working

### ISSUE THREAD

**Issue by vagishmm** [cesarvr/pdf-generator#70]
If I add this code to my project iOS 9 unable to trigger onDeviceReady event. But in iOS 11 it is working fine. Please help me in this case.

**Comment by cesarvr** [comment]
Sorry for the late response, I have tried this [example](https://github.com/cesarvr/pdf-generator-example) in the emulator iOS9.0 and is working, I think is not a compatibility problem.  It seems it have to do with your Cordova version. 

<img width="380" alt="screen shot 2018-03-09 at 12 18 53" src="https://user-images.githubusercontent.com/3899337/37205219-3ff1d4a8-2394-11e8-8d1f-eb10cf5de66a.png">

Cheers.
