### ISSUE TITLE
Ios - [ShareSheet] ERROR: timed out waiting to establish a connection to the ShareUI view service extension.

### ISSUE THREAD

**Issue by jshupptechnologies** [cesarvr/pdf-generator#73]
Doesn't working on ios

I have tried using both method fromData and fromURL also tried both type but didn't worked at all.
My code using fromUrl method:

       let options = {
	        documentSize: 'A3',
	        type: 'base64'
        }

       let fileUrl = "./assets/html/1.html";

	cordova.plugins.pdf.fromURL(fileUrl, options).then((res)=>{
	    	console.log('res of pdf >>>>>>>>>',res);
	}).catch((err)=>{
	    console.log('export error >>>>>>>>>',err);
	})

**Expected behavior**:
- I want to download | print | share pdf from html source code

**Cordova**: 6.5.0
**Ionic**: 3.9.2
**plugin-version**: 2.0.1
**ios-version**: 11.0.1

**Comment by cesarvr** [comment]
To get some file from file system in iOS you need the cordova-plugin-file, also you can take a look at this [example](cordova-plugin-file).

Cheers.

**Comment by jshupptechnologies** [comment]
Thanks ended up using base64 data but using type share is still not working for me on ios.

**Comment by jshupptechnologies** [comment]
Thanks ended up using base64 data but using type share is still not working for me on ios.
