### ISSUE TITLE
CSS style 

### ISSUE THREAD

**Issue by smart548** [cesarvr/pdf-generator#80]
I've tried to add some css (not in-line) to the html which I want to use to make the pdf document but I noticed it is not replicated into the built pdf. Is that possible to achive or only in-line styling is allowed?
Thank you all.

**Comment by cesarvr** [comment]
Hi, you can use non in-line CSS you just need to make it reachable to the plugin, check [this examples](https://github.com/cesarvr/pdf-generator-example)

**Comment by smart548** [comment]
Hola Cesar,
thank you for replying. I feel sorry to bother you but I need some more explanations. As my comprehension, what I need to do is set the "baseUrl" parameter as an option, so that what I end up having is something like:

let options = {
      documentSize: 'A4',
      type: 'base64',
      baseUrl: './'             //<------------------------
    }

What  I do not understand is how I should set this parameter. I need to read the rules included in a .scss file which is located in the same path as the typescript file (in which I call the plugin).
How can I achieve that?

p.s. I am building my app with:
- ionic 3.9
- angular 4.6
- cordova

Thank you again.

**Comment by smart548** [comment]
Hey Cesar,
I've tried to build your example app on an iPad equipped with iOS 10 but every time I try to generate a pdf document, the app remains stuck with the spinner still rotating. Xcode isn't giving me back any errors, neither do safari. What should I do?

**Comment by smart548** [comment]
Just to add some more info: I've opened the .ipa generated and discovered my built css is located in root/www/build.

**Comment by cesarvr** [comment]
I updated the plugin and added the functionality that allow you to load css from your file system , to learn how to use take a look at the [sample app](https://github.com/cesarvr/pdf-generator-example) I fix some errors there as well (thanks for reporting) related to the progress bar, I test it with iOS 9 - 11 so it should work any problem let me know 👍.


basically you assuming your CSS is in the root folder of **www** , you can use it inside your HTML by doing: 
```
pdf.fromData("
<head>
    <link rel=\"stylesheet\" href=\"www/test.css\">
</head>
<body>
   <h1> Hello World </h1>
</body>",
                        opts)
                    .then(function(s){ console.log('success', s)})
                    .catch(function(e) { console.log('err', e)});
```

For android you need to use `file:///android_asset/www/test.css`

**Comment by smart548** [comment]
Thank you for finding the time to reply; 
does the baseUrl option need to be set though?

**Comment by cesarvr** [comment]
No. At the moment the plugin make the assumption that if you passing raw data, it will use css available in FS and if you are using some cloud template then it will work as expected.

**Comment by smart548** [comment]
Thank you Cesar! You have been helpful :)

**Comment by smart548** [comment]
One last thing Cesar: now that I can import my .css sheets I am seeing the generated pdf look "weird"(attached screenshot).
The same template in HTML looks different (it is correctly formatted). Notice that I only added the red color to the first element on my css,

Thank you again.
![schermata 2018-05-07 alle 17 40 04](https://user-images.githubusercontent.com/16303667/39711481-2286a118-5220-11e8-9845-36fbddcf12f8.png)

**Comment by smart548** [comment]
I've fixed that setting a min and max-width for the html template ;)
