### ISSUE TITLE
Multiple Page Pdf

### ISSUE THREAD

**Issue by ebarolo** [cesarvr/pdf-generator#87]
Hi, 
How it's possibile to generate multiple page pdf from html? 

Thank You

**Comment by lukawal-miller** [comment]
Just add to your HTML  `style="page-break-before: always;` on the last element and everything after that  will be on next page.

**Comment by merbin2012** [comment]
> Hi @ebarolo the plugin draw the page in a browser behind the scene, so you need to put enough padding in between the content.
> 
> Example:
> 
> ```
> <h1 style="margin-bottom: 900px">page 1</h1>
>  
> 
> 
> <h1 style="margin-bottom: 900px">page 2</h1>
>  
> ```
> 
> You need to play with those values, to achieve the desired effect.
> 
> Also here is some examples one of it does multi-page. [pdf-generator-example](https://github.com/cesarvr/pdf-generator-example)

This is not working

**Comment by merbin2012** [comment]
> Just add to your HTML `style="page-break-before: always;` on the last element and everything after that will be on next page.

Thank you, this is working
